### PR TITLE
Fixed issue "Window doesn't quit on using X quit button"

### PR DESCRIPTION
**Pull request by arihan01**

### CODE REVIEW

**Comment by bluishhh** [comment]
!bounty 20

**Comment by bluishhh** [comment]
enthu points^

**Comment by bluishhh** [comment]
!bounty 40

**Comment by bluishhh** [comment]
bounty^

**Comment by bluishhh** [comment]
!bounty 5

**Comment by bluishhh** [comment]
!bounty 65

**Comment by bluishhh** [comment]
20 enthu + 40 bounty + 5 brownie

**Comment by ArnavKumar7** [comment]
!bounty 35

**Pull request merged**
