### PR TITLE
UI Changes to Puzzle Game #30

### PR DESCRIPTION
**Pull request by SarthakSKumar**
Sarthak S Kumar
PES2UG21CS482
Fixes: #30

### CODE REVIEW

**Comment by SarthakSKumar** [comment]
Fixed Merge Conflicts

**Comment by bluishhh** [comment]
!bounty 100

**Comment by bluishhh** [comment]
80 bounty + 20 brownie (I troubled him alot) :)

**Comment by ArnavKumar7** [comment]
!bounty 80

**Comment by ArnavKumar7** [comment]
!bounty 80

**Comment by bluishhh** [comment]
!bounty 80

**Comment by ArnavKumar7** [comment]
!bounty 80

**Pull request merged**
