### PR TITLE
Fixed Title position in ther puzzle game GUI

### PR DESCRIPTION
**Pull request by SarthakSKumar**
Sarthak S Kumar
PES2UG21CS482
Fixes: #26

### CODE REVIEW

**Comment by bluishhh** [comment]
!button 40

**Comment by bluishhh** [comment]
!bounty 40

**Comment by NavinShrinivas** [comment]
on further review, this pr will be assigned 30 points!

**Comment by NavinShrinivas** [comment]
!bounty 30

**Comment by bluishhh** [comment]
30 bounty + 10 enthu

**Comment by ArnavKumar7** [comment]
20+10

**Pull request merged**
